# docker-compose.yml
version: "3.8"

services:
  api:
    image: tinsu2/financial-ocr:latest
    ports:
      - "7000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - URL=${URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
      - worker
    volumes:
      - ./uploads:/app/uploads

  worker:
    image: tinsu2/financial-ocr:latest
    command: celery -A tasks worker --loglevel=info
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: redis:7.2-alpine

volumes:
  uploads:
