# docker-compose.yml
version: '3.8'

services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - worker
    volumes:
      - ./uploads:/app/uploads

  worker:
    build: ./app
    command: celery -A tasks worker --loglevel=info
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: redis:7.2-alpine

volumes:
  uploads: